<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cbl</string>
		<string>cpy</string>
		<string>cob</string>
		<string>dds</string>
		<string>ss</string>
		<string>wks</string>
	</array>
	<key>name</key>
	<string>COBOL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^[0-9 a-zA-Z\*][0-9 a-zA-Z\*][0-9 a-zA-Z\*][0-9 a-zA-Z\*][0-9 a-zA-Z\*][0-9 a-zA-Z\*][\*/].*$)</string>
			<key>name</key>
			<string>comment.line.set.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)((?i)\$\s*set.*ilusing)(?:$|.*$)</string>
			<key>name</key>
			<string>keyword.control.import</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)((?i)\$\s*set)(?:$|\s.*$)</string>
			<key>name</key>
			<string>comment.line.set.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)((?i)\$\s*(?i:if|else|end|display))(?:$|\s.*$)</string>
			<key>name</key>
			<string>meta.preprocessor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^[0-9][0-9][0-9][0-9][0-9][0-9])</string>
			<key>name</key>
			<string>comment.line.rem.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^      \*.*$|^\*.*$)</string>
			<key>name</key>
			<string>comment.line.rem.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*&gt;.*$)</string>
			<key>name</key>
			<string>comment.line.rem.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[hHxX]"\h*"</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[hHxX]".*"</string>
			<key>name</key>
			<string>invalid.illegal.hexadecimal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[oO]"[0-7]*"</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[oO]".*"</string>
			<key>name</key>
			<string>invalid.illegal.octal.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.start.bracket.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.cobol</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.end.bracket.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>simple numerics in () and []</string>
			<key>match</key>
			<string>(?&lt;=(\(|\[))((\-\+)*[0-9 \.\+\-\*\/]+)(?=(\)|\]))</string>
			<key>name</key>
			<string>constant.numeric.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(\-|\+)?((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?(?=\s|\.|,|\))</string>
			<key>name</key>
			<string>constant.numeric.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:true|false|null|nulls)(?=\s|\.)</string>
			<key>name</key>
			<string>constant.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:zeroes|zeros|zero|spaces|space|quotes|quote|low-values|low-value|high-values|high-value)(?=\s|\.)</string>
			<key>name</key>
			<string>constant.figurative.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:EXEC\s*SQL)</string>
			<key>end</key>
			<string>(?i:END-EXEC)</string>
			<key>name</key>
			<string>meta.embedded.cobol,string.quoted,source</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:EXEC\s*CICS)</string>
			<key>end</key>
			<string>(?i:END-EXEC)</string>
			<key>name</key>
			<string>meta.embedded.cobol,string.quoted,source</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:EXEC\s*ADO)</string>
			<key>end</key>
			<string>(?i:END-EXEC)</string>
			<key>name</key>
			<string>meta.embedded.cobol,string.quoted,source</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>("|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>('|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[zZ]"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>("|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[zZ]'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[nN]"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>("|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[nN]'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:identification\s*division|identification|enum-id|property-id|getter|setter|valuetype-id|author|date-written|date-compiled|entry|function-id|attribute|interface-id|method-id|factory|ctl|class-control|options|environment\s*division|environment|configuration\s*section|configuration|decimal-point|call-convention|source-computer|object-computer|special-names|repository|input-output\s*section|input-output|file\s*section|file-control|select|optional|i-o-control|data\s*division|working-storage\s*section|working-storage|section|local-storage|linkage\s*section|linkage|communication|report|screen\s*section|fd|rd|cd|sd|printing|procedure\s*division|procedure|declaratives|installation|security|based-storage|size|font)\b[^-]</string>
			<key>name</key>
			<string>keyword.identifiers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?i:end class|end property|end method|end program|declare|return-code|as||stop\srun|stop)(?=\s|\.|$)</string>
			<key>name</key>
			<string>keyword.identifiers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?i:sync\s*(?i:on))(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.other.sync.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?i:try|finally|catch|end-try|throw)\b</string>
			<key>name</key>
			<string>keyword.control.catch-exception.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i)(?i:else|when|select|use|thru|varying|giving|remainder|tallying|through|until|execute|returning|using|copy|replace)(?=\s)</string>
			<key>name</key>
			<string>keyword.otherverbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:assign|external|organization|indexed|column|plus|line\*s*sequential|sequential|access|dynamic|relative|label|block|contains|standard|records|record\s*key|record|is|alternate|duplicates|disk|disc|mode|random)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.identifers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:end-accept|end-add|end-sync|end-call|end-compute|end-delete|end-display|end-divide|end-evaluate|end-multiply|end-of-page|end-perform|end-read|end-receive|end-return|end-rewrite|end-search|end-start|end-string|end-subtract|end-unstring|end-write|program|class|interface|function|enum|interface)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.verbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:by value|by reference|by content|property-value)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.other.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:attr-string|automatic|auto-skip|control|full|required|of|input|output|i-o|extend|file|error|exception|overflow|goto|on|proceed|procedure|through|invalid|data|normal|eop|end-of-page|returning|to|for|giving|into|by|remainder|also|not|numeric|free|depending|converting|replacing|after|before|all|leading|first|initial|reference|content|are|values|value|ascending|descending|key|retry|until|varying|when|equals|equal|with|no|advancing|up|down|uccurs|lock|length|delimited|count|delimiter|redefines|from|raising|status|class|upon|line|position|col|reporting|arithmetic|localize|program|class|interface|function|in|at||end)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.identifers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:binary-char|binary-char-unsigned|binary-short|binary-short-unsigned|binary.long|binary-long-unsigned|binary-long|binary-double|binary-double-unsigned|float-short|float-long|condition-value|characters|character\s*type|character|comma|decimal|object\sreference|object|list|dictionary|unsigned)(?=\s|\.)</string>
			<key>name</key>
			<string>storage.type.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.verb.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>program-id. ssss </string>
			<key>match</key>
			<string>(?i:program-id)\.\s*((?:[a-zA-Z][a-zA-Z0-9\-_]*|[a-zA-Z]))</string>
			<key>name</key>
			<string>keyword.program-id.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.verb.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>class-id ssss </string>
			<key>match</key>
			<string>(?i:class-id|inherits)\.\s*((?:[a-zA-Z][a-zA-Z0-9\-\.]*|[a-zA-Z]))</string>
			<key>name</key>
			<string>keyword.class-id.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.verb.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>class-id ssss </string>
			<key>match</key>
			<string>(?i:class-id|inherits)\s*((?:[a-zA-Z][a-zA-Z0-9\-\.]*|[a-zA-Z]))</string>
			<key>name</key>
			<string>keyword.class-id.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>invoke type sss:.. </string>
			<key>match</key>
			<string>(?i:invoke)\s*(?i:type)\s*([0-9a-zA-Z\.]*)</string>
			<key>name</key>
			<string>keyword.invoketype</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.self.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.cobol</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:self)::\s*([0-9a-zA-Z\.]*)</string>
			<key>name</key>
			<string>keyword.invoke.self</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>invoke sss:.. </string>
			<key>match</key>
			<string>(?i:invoke)\s*([0-9a-zA-Z\.]*)</string>
			<key>name</key>
			<string>keyword.invoketype</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>invoke sss:.. </string>
			<key>match</key>
			<string>(::)\s*([0-9a-zA-Z\.]*)</string>
			<key>name</key>
			<string>keyword.invoketype</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.cobol</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:type\s+)([0-9a-zA-Z\.]*)</string>
			<key>name</key>
			<string>storage.type.source.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:accept|add|address|allocate|call|cancel|chain|close|commit|compute|continue|delete|disable|display|bell|divide|enable|enter|evaluate|exhibit|named|exit|free|generate|go\s*to|go|goback|initialize|initiate|inspect|merge|set|move|multiply|open|perform|purge|raise|read|receive|release|return|rewrite|rounded|rollback|search|send|sort|start|service|subtract|suppress|terminate|then|unlock|string|unstring|validate|write)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.verbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+sS$9aAbBxXnNzZ/,.]*\([0-9]*\)[vV\.][-+s$9aAbBsSnNxXzZ/,]*\([0-9]*\)</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+sS$9aAbBsSnNxXzZ/,.]*\([0-9]*\)[Vv\.][-+s$9aAbBsSnNxXzZ/,]*</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+sS$9aAbBsSnNxXzZ/,.]*\([0-9]*\)</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[sS]?[9aAbBsSnNxXzZ]*[Vv][9aAxbXzZ]*</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+$9aAbBsSnNxXzZ/,.]*</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:comp-1|comp-2|comp-3|comp-x|comp-5|comp|computational|usage display|binary|mutex-pointer|thread-pointer|sempahore-pointer|event-pointer|procedure-pointer|pointer|occurs|any|times|blank\s*screen|blank|usage)(?=\s|\.)</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?:foreground-color|background-color|highlight|blink)\b</string>
			<key>name</key>
			<string>keyword.screens.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)if\s+((not)\s+)(then)</string>
			<key>name</key>
			<string>keyword.verbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?:if|else|then|end-if)\b</string>
			<key>name</key>
			<string>keyword.control.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:internal|public|protected|private|static|new|abstract|override|readonly)(?=\s|\.)</string>
			<key>name</key>
			<string>storage.modifier.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s(=|&lt;|&gt;|&lt;=|&gt;=|&lt;&gt;|\+|\-|\*|\/|b-and|b-or|b-xor|b-not|b-left|b-right|and|or|not)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.operator.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:class-id|program-id)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.verbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:SYSIN|SYSIPT|SYSOUT|SYSLIST|SYSLST|PRINTER|SYSERR|CONSOLE|C01|C02|C03|C04|C05|C06|C07|C08|C09|C10|C11|C12|FORMFEED|SWITCH-1|SWITCH-2|SWITCH-3|SWITCH-4|SWITCH-5|SWITCH-6|SWITCH-7|SWITCH-8|next)(?=\s|\.)</string>
			<key>name</key>
			<string>support.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:end-xml|processing.*procedure|xml\sparse|xml|xml-text|xml-schema|xml-ntext|xml-namespace|xml-namespace-prefix|xml-event|xml-declaration|xml-code|xml-nnamespace-prefix|xml-nnamespace)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.xml.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:alter)(?=\s|\.)</string>
			<key>name</key>
			<string>invalid.illegal.cobol</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cobol</string>
</dict>
</plist>
