<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cbl</string>
		<string>cpy</string>
		<string>cob</string>
		<string>dds</string>
		<string>ss</string>
		<string>wks</string>
	</array>
	<key>name</key>
	<string>COBOL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^[0-9 a-zA-Z\*\-][0-9 a-zA-Z\\*\-][0-9 a-zA-Z\*\-][0-9 a-zA-Z\*\-][0-9 a-zA-Z\*\-][0-9 a-zA-Z\*\-][\*/].*$)</string>
			<key>name</key>
			<string>comment.line.set.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)((?i)\$\s*set.*ilusing)(?:$|.*$)</string>
			<key>name</key>
			<string>keyword.control.import</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)((?i)\$\s*set)(?:$|\s.*$)</string>
			<key>name</key>
			<string>comment.line.set.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)((?i)\$\s*(?i:if|else|end|display))(?:$|\s.*$)</string>
			<key>name</key>
			<string>meta.preprocessor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)&gt;&gt;(?i:if|else|elif|end-if)(?:$|\s.*$)</string>
			<key>name</key>
			<string>meta.preprocessor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^[0-9][0-9][0-9][0-9][0-9][0-9])</string>
			<key>name</key>
			<string>comment.line.rem.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^      \*.*$|^\*.*$)</string>
			<key>name</key>
			<string>comment.line.rem.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*&gt;.*$)</string>
			<key>name</key>
			<string>comment.line.rem.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[hHxX]'\h*'</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[hHxX]'.*'</string>
			<key>name</key>
			<string>invalid.illegal.hexadecimal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[hHxX]"\h*"</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[hHxX]".*"</string>
			<key>name</key>
			<string>invalid.illegal.hexadecimal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[oO]"[0-7]*"</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[oO]".*"</string>
			<key>name</key>
			<string>invalid.illegal.octal.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.start.bracket.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.cobol</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.end.bracket.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>simple numerics in () and []</string>
			<key>match</key>
			<string>(?&lt;=(\(|\[))((\-\+)*[0-9 ,\.\+\-\*\/]+)(?=(\)|\]))</string>
			<key>name</key>
			<string>constant.numeric.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(\-|\+)?((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?(?=\s|\.|,|\))</string>
			<key>name</key>
			<string>constant.numeric.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:true|false|null|nulls)(?=\s|\.|$)</string>
			<key>name</key>
			<string>constant.language.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:zeroes|zeros|zero|spaces|space|quotes|quote|low-values|low-value|high-values|high-value)(?=\s|\.)</string>
			<key>name</key>
			<string>constant.language.figurative.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:EXEC\s*SQL)</string>
			<key>end</key>
			<string>(?i:END-EXEC)</string>
			<key>name</key>
			<string>meta.embedded.cobol,string.quoted,source</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:EXEC\s*CICS)</string>
			<key>end</key>
			<string>(?i:END-EXEC)</string>
			<key>name</key>
			<string>meta.embedded.cobol,string.quoted,source</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:EXEC\s*ADO)</string>
			<key>end</key>
			<string>(?i:END-EXEC)</string>
			<key>name</key>
			<string>meta.embedded.cobol,string.quoted,source</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>("|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>('|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[zZ]"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>("|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[zZ]'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[nN]"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>("|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cobol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>[nN]'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cobol</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cobol</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:identification\s*division|identification|enum-id|property-id|getter|setter|valuetype-id|author|date-written|date-compiled|entry|function-id|attribute|interface-id|method-id|factory|ctl|class-control|options|environment\s*division|environment|configuration\s*section|configuration|decimal-point|call-convention|source-computer|object-computer|special-names|repository|input-output\s*section|input-output|file\s*section|file-control|select|optional|i-o-control|data\s*division|working-storage\s*section|working-storage|section|local-storage|linkage\s*section|linkage|communication|report|screen\s*section|fd|rd|cd|sd|printing|procedure\s*division|procedure|debugging|declaratives|installation|security|based-storage|size|font)\b[^-]</string>
			<key>name</key>
			<string>keyword.identifiers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?i:end class|end property|end if|exit method|method|end program|create|reset|instance|delegate|declare|debug-line|debug-name|debug-contents|sort-return|return-code|as||stop\srun|stop)(?=\s|\.|$)</string>
			<key>name</key>
			<string>keyword.identifiers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?i:sync\s*(?i:on))(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.other.sync.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?i:try|finally|catch|end-try|throw)(?=\s|\.|$)</string>
			<key>name</key>
			<string>keyword.control.catch-exception.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i)(?i:else|when|select|use|thru|varying|giving|remainder|tallying|through|until|execute|returning|using|copy|replace)(?=\s)</string>
			<key>name</key>
			<string>keyword.otherverbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:assign|external|organization|indexed|column|plus|line\*s*sequential|sequential|access|dynamic|relative|label|block|contains|standard|records|record\s*key|record|is|alternate|duplicates|disk|disc|mode|random)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.identifers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:function)\s(?i:date-to-yyyymmdd|year-to-yyyy|day-to-yyyyddd|e|variance|integer-of-date|rem|pi|factorial|sqrt|log10|fraction-part|mean|exp|log|char|day-of-integer|date-of-integer|exp10|atan|integer-part|tan|ord|sin|cos|midrange|addr|acos|asin|annuity|present-value|integer-of-day|ord-max|ord-min|random|integer-of-date|sum|sign|standard-deviation|median|reverse|abs|upper-case|lower-case|char-national|numval|mod|range|length-an|numval-c|current-date|national-of|display-of|when-compiled|integer-of-boolean)</string>
			<key>name</key>
			<string>support.function.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:end-accept|end-add|end-sync|end-call|end-compute|end-delete|end-display|end-divide|end-if|end-evaluate|end-multiply|end-of-page|end-perform|end-read|end-receive|end-return|end-rewrite|end-search|end-start|end-string|end-subtract|end-unstring|end-write|program|class|interface|function|enum|interface)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.verbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?:by value|by reference|by content|property-value)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.other.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:attr-string|automatic|auto-skip|footing|next|group|indicate|page-counter|line-counter|source|control|full|required|of|input|output|i-o|extend|file|error|exception|overflow|goto|on|proceed|procedures|procedure|through|invalid|data|normal|eop|returning|to|for|giving|into|by|remainder|also|numeric|free|depending|converting|replacing|after|before|all|leading|first|recursive|initial|reference|content|are|renames|like|format\stime|values|value|ascending|descending|key|retry|until|varying|when|with|no|advancing|up|down|uccurs|lock|length|delimited|count|delimiter|redefines|from|raising|status|class|upon|lines|line|position|col|reporting|arithmetic|localize|program|class|interface|function|in|at|end|page)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.identifers.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:binary-char|binary-char-unsigned|binary-short|binary-short-unsigned|binary.long|binary-long-unsigned|binary-long|binary-double|binary-double-unsigned|float-short|float-long|condition-value|characters|character\s*type|character|comma|decimal|object\sreference|object|list|dictionary|unsigned)(?=\s|\.)</string>
			<key>name</key>
			<string>storage.type.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.verb.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>program-id. ssss </string>
			<key>match</key>
			<string>(?i:program-id)\.\s*((?:[a-zA-Z][a-zA-Z0-9\$\-_]*|[a-zA-Z]))</string>
			<key>name</key>
			<string>keyword.program-id.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.verb.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>class-id ssss </string>
			<key>match</key>
			<string>(?i:class-id|inherits|implements)\.\s*((?:[a-zA-Z][a-zA-Z0-9\-\.]*|[a-zA-Z]))</string>
			<key>name</key>
			<string>keyword.class-id.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.verb.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>class-id ssss </string>
			<key>match</key>
			<string>(?i:class-id|inherits|implements)\s*((?:[a-zA-Z][a-zA-Z0-9\-\.]*|[a-zA-Z]))</string>
			<key>name</key>
			<string>keyword.class-id.cobol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.identifers.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>invoke type sss:.. </string>
			<key>match</key>
			<string>(?i:invoke)\s*(?i:type)</string>
			<key>name</key>
			<string>keyword.invoketype</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.self.cobol</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:self)::</string>
			<key>name</key>
			<string>keyword.invoke.self</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>invoke sss:.. </string>
			<key>match</key>
			<string>(?i:invoke)\s*([0-9a-zA-Z_\-\.]*)</string>
			<key>name</key>
			<string>keyword.invoketype</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.cobol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>invoke sss:.. </string>
			<key>match</key>
			<string>(::)\s*([0-9a-zA-Z_\-\.]*)</string>
			<key>name</key>
			<string>keyword.invoketype</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.cobol</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.cobol</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:type\s+)([0-9a-zA-Z\.]*)</string>
			<key>name</key>
			<string>storage.type.source.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:accept|add|address|allocate|call|cancel|chain|close|commit|compute|continue|delete|disable|display|bell|divide|enable|enter|if|evaluate|exhibit|named|exit|free|generate|go\s*to|go|goback|initialize\sonly|initialize|initiate|inspect|merge|set|move|multiply|open|perform|purge|raise|read|receive|release|return|rewrite|rounded|rollback|search|send|sort|start|service|subtract|suppress|terminate|then|unlock|string|unstring|validate|write)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.verbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+sS$9aAbBxXnNzZ/,.]*\([0-9]*\)[vV\.][-+s$9aAbBsSnNxXzZ/,]*\([0-9]*\)</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+sS$9aAbBsSnNxXzZ/,.]*\([0-9]*\)[Vv\.][-+s$9aAbBsSnNxXzZ/,]*</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+sS$9aAbBsSnNxXzZ/,.]*\([0-9]*\)</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[sS]?[9aAbBsSnNxXzZ]*[Vv][9aAxbXzZ]*</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:picture|pic)\s+[-+$9aAbBsSnNxXzZ/,.vV]*</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:computational-1|comp-1|computational-2|comp-2|computational-3|comp-3|computational-4|comp-4|computational-x|comp-x|computational-5|comp-5|computational-6|comp-6|computational-n|comp-n|packed-decimal|index|float|double|signed-short|unsigned-short|signed-int|unsigned-int|signed-long|unsigned-long|comp|computational|usage\sis\sdisplay|usage\sis\sfont|usage display|binary|mutex-pointer|thread-pointer|sempahore-pointer|event-pointer|procedure-pointer|pointer|handle|window|subwindow|control-type|thread|menu|variant|layout-manager|occurs|typedef|any|times|blank\s*screen|blank|usage\sis|is\spartial|usage|just|right)(?=\s|\.)</string>
			<key>name</key>
			<string>storage.type.picture.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(?i)(?:foreground-color|background-color|highlight|blink)\b</string>
			<key>name</key>
			<string>keyword.screens.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:internal|public|protected|private|static|new|abstract|override|readonly|property)(?=\s|\.)</string>
			<key>name</key>
			<string>storage.modifier.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s(?i:=|&lt;|&gt;|&lt;=|&gt;=|&lt;&gt;|\+|\-|\*|\/|b-and|b-or|b-xor|b-not|b-left|b-right|and|or|not|equals|equal)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.operator.comparison.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:class-id|program-id)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.verbs.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:sysin|sysipt|sysout|syslist|syslst|printer|syserr|console|c01|c02|c03|c04|c05|c06|c07|c08|c09|c10|c11|c12|formfeed|switch-1|switch-2|switch-3|switch-4|switch-5|switch-6|switch-7|switch-8|next)(?=\s|\.)</string>
			<key>name</key>
			<string>support.type.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:end-xml|processing.*procedure|xml\sparse|xml|xml-information|xml-text|xml-schema|xml-ntext|xml-namespace|xml-namespace-prefix|xml-event|xml-declaration|xml-code|xml-nnamespace-prefix|xml-nnamespace)(?=\s|\.)</string>
			<key>name</key>
			<string>keyword.xml.cobol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:alter)(?=\s|\.)</string>
			<key>name</key>
			<string>invalid.illegal.cobol</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cobol</string>
</dict>
</plist>
